apiVersion: v1
kind: Namespace
metadata:
  name: mailhog
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: mailhog
  labels:
    app: mailhog
spec:
  ports:
    - port: 8025
      targetPort: 8025
      nodePort: 30025  # Füge dies hinzu, um den Port explizit festzulegen (zwischen 30000-32767)
      name: mailhog-ui
    - port: 1025
      targetPort: 1025
      nodePort: 30026  # Optional für den zweiten Port
      name: mailhog-smtp
  selector:
    app: mailhog
  type: NodePort  # Ändere den Service-Typ auf NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: mailhog
spec:
  selector:
    matchLabels:
      app: mailhog
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - image: mailhog/mailhog:latest
          name: mailhog
          ports:
            - containerPort: 8025
              name: mailhog-ui
            - containerPort: 1025
              name: mailhog-smtp
          securityContext:
            privileged: false
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"