spring:
  jpa:
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:443/realms/dance-network
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

token:
  converter:
    principal-attribute: preferred_username
    resource-id: dance-network-admin