spring:
  jpa:
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:443/realms/dance-network
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  mail:
    host: localhost
    port: 30026
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enabled: false

token:
  converter:
    principal-attribute: preferred_username
    resource-id: dance-network-admin

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"